name:                scroll-list
version:             1.1.0.0
github:              "fesanmar/scroll-list"
license:             BSD3
author:              "Felipe Santa-Cruz"
maintainer:          "fesanmar@gmail.com"
copyright:           "2021 Felipe Santa-Cruz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            This package provides functions for relocate an item within a list.
category:            List

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fesanmar/scroll-list#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - extra >= 1.7.9 && < 2.0.0

tests:
  scroll-list-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scroll-list
    - hspec
